package com.revature.foundations.Util.exceptions;

public class DataSourceException extends RuntimeException {

    public DataSourceException(String message, Throwable cause) {
        super(message, cause);
    }

}
